CREATE TABLE `lasiodora_parahybana`.`real_estate_offer` ( 
  `id` INT NOT NULL AUTO_INCREMENT,
  `market_id` INT NULL DEFAULT 21,
  `OBID` INT NULL,
  `created_at` DATE NULL,
  `provider_id` INT NULL,
  `provider_object_id` VARCHAR(100) NULL,
  `real_estate_type` VARCHAR(50) NULL,
  `real_estate_type_detail` VARCHAR(200) NULL,
  `com_type` VARCHAR(50) NULL DEFAULT 'kaufen',
  `country` VARCHAR(30) NULL DEFAULT 'Deutschland',
  `state` VARCHAR(50) NULL,
  `district` VARCHAR(150) NULL,
  `city` VARCHAR(150) NULL,
  `postal_code` VARCHAR(10) NULL,
  `street` VARCHAR(100) NULL,
  `street number` VARCHAR(40) NULL,
  `offer_title` VARCHAR(500) NULL,
  `description` VARCHAR(15000) NULL,
  `level` VARCHAR(30) NULL,
  `buy_price` DECIMAL(8) NULL,
  `rent` DECIMAL(8) NULL,
  `rent_with_heating` DECIMAL(8) NULL,
  `additional_cost` DECIMAL(8) NULL,
  `room_number` DECIMAL(8) NULL,
  `living_space` DECIMAL(8) NULL,
  `month` DECIMAL(8) NULL,
  `url` VARCHAR(1000) NULL,
  `phone_number` VARCHAR(100) NULL,
  `create_date_on_site` DECIMAL(8) NULL,
  `commercial` DECIMAL(8) NULL,
  PRIMARY KEY (`id`));
 

